version: "3"
services:
  ubuntu:
   tty: true
   build: ./ubuntu
   networks:
    - ubuntu_ssh
  kali:
   tty: true
   build: ./kali 
   networks:
    - ubuntu_ssh
  dvwa:
   tty: true
   image: vulnerables/web-dvwa:latest
   ports:
     - "80:80"
   networks:
    - ubuntu_ssh

networks:
  ubuntu_ssh:
   external: true
   name: ubuntu_ssh
